# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nsXQ824nKaqoAUKxup9STgUSkauaJLi

# Task 1
Using the Pandas library, load a CSV file and perform basic data analysis tasks, such as
calculating the average of a selected column. Additionally, use Matplotlib to create
visualizations, including bar charts, scatter plots, and heatmaps, to analyze the data. Provide
insights and observations based on the analysis and visualizations.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Students_Performance.csv')
df

df.head()

df.tail()

df.describe()

df.info()

df.count()

df.shape

df.size

df.columns

df.isnull().sum()

# No Null value found in the dataset

df['parental level of education'].unique()

df.dtypes

reading_score = df.groupby(df['test preparation course'])['reading score'].mean()
reading_score

reading_score.plot.bar()

# Analysis of the bar plot:
# The bar plot displays the average reading scores for students based on their 'test preparation course' status.
# It clearly indicates that students who completed the test preparation course have a higher average reading score
# (approximately 73.89) compared to those who did not complete the course (approximately 66.53).
# This suggests a positive correlation between completing the test preparation course and higher reading scores.

df['total score'] = df['math score'] + df['reading score'] + df['writing score']

plt.figure(figsize=(16,8))
sns.barplot(x='math score', y='total score', hue='math score', data=df, palette='viridis', legend=False)
plt.title("Comparison of Scores on Basis of Math Score")
plt.xlabel("Math Score")
plt.ylabel("Total Score")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Analysis of the bar plot (math score vs. total score):
# This bar plot illustrates the relationship between students' individual 'math score' and their 'total score'.
# Higher math scores directly correspond to higher total scores.
# The visualization effectively demonstrates how a student's performance in mathematics contributes significantly.

plt.figure(figsize=(10,6))
sns.histplot(x='reading score', y='writing score', data=df, palette='viridis')
plt.title("comparision between reading and writing score")
plt.xlabel("reading score")
plt.ylabel("writing score")
plt.show()

# Analysis of the histogram (reading score vs. writing score):
# This 2D histogram visualizes the joint distribution of 'reading score' and 'writing score'.
# A strong positive correlation is evident
# Highest cluster around the average scores for both subjects.
# It is observed for reading scores in the range of approximately 60-80 and writing scores in a similar range of 60-80.
# Dataset's overall mean reading score (approximately 69.17) and mean writing score (approximately 68.05).

df.groupby(['lunch'])['total score'].mean()

plt.figure(figsize=(10,6))
sns.scatterplot(x='lunch', y='total score', data=df, palette='viridis')
plt.title("scatter plot")
plt.xlabel("lunch")
plt.ylabel("total score")
plt.show()

# Analysis of the scatter plot (lunch vs. total score):
# This scatter plot demonstrates a clear disparity in 'total score' based on 'lunch' status.
# It is observed, higher total scores (mean ~212.5) than those with 'free/reduced' lunch (mean ~186.6).
# This suggests a potential correlation between socio-economic factors, indicated by lunch status, and academic performance.

df.groupby(['parental level of education'])['total score'].mean()

plt.figure(figsize=(10,7))
sns.barplot(x='parental level of education', y='total score', hue='parental level of education', data=df, palette='pastel')
plt.title("Average Total Score by Parental Level of Education")
plt.xlabel("Parental Level of Education")
plt.ylabel("Total Score")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Analysis of the bar plot (parental level of education vs. total score):
# This bar plot visualizes the average 'total score' across different parental education levels.
# Students whose parents have a 'master's degree' show the highest average total score (approximately 220.8).
# This is closely followed by 'bachelor's degree' (around 215.8).
# 'Associate's degree' parents correspond to an average of about 208.7, and 'some college' to 205.4.
# The lowest average total scores are observed for students whose parents completed 'high school' (around 189.3)
# And 'some high school' (around 195.3).
# This suggests that parental educational background may be a contributing factor to a student's overall academic performance.

pd.get_dummies(df['gender'])

# Normalization and Standardization

from sklearn.preprocessing import MinMaxScaler, StandardScaler

numeric  = df.select_dtypes(include='number')

obj1 = MinMaxScaler()
obj2 = StandardScaler()
data1= obj1.fit_transform(numeric)
data2= obj2.fit_transform(numeric)

data1

data2

numeric.boxplot()

def get_iqr_bounds(series):
  Q1 = series.quantile(0.25)
  Q3 = series.quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  return lower_bound, upper_bound

math_low, math_high = get_iqr_bounds(df['math score'])
read_low, read_high = get_iqr_bounds(df['reading score'])
write_low, write_high = get_iqr_bounds(df['writing score'])
total_low, total_high = get_iqr_bounds(df['total score'])

print(f"Range of math score: {math_low:.2f} to {math_high:.2f}")
print(f"Range of reading score: {read_low:.2f} to {read_high:.2f}")
print(f"Range of writing score: {write_low:.2f} to {write_high:.2f}")
print(f"Range of total score: {total_low:.2f} to {total_high:.2f}")

df_cleaned = df[(df['math score'] >= 27) & (df['math score'] <= 107) &
                (df['reading score'] >= 30) & (df['reading score'] <= 109) &
                (df['writing score'] >= 26) & (df['writing score'] <= 110) &
                (df['total score'] >= 88) & (df['total score'] <= 320)]
df_cleaned.boxplot()

# All outliers removed from the dataset.

"""END

"""























